import React from 'react';
import FeatureCard from '../components/FeatureCard';
import Header from '../components/Header';
import Footer from '../components/Footer';
import '../styles/InfoPages.css';

const FeaturesPage = () => {
  const features = [
    {
      title: "AI-Powered Meal Plans",
      description: "Get personalized weekly meal plans generated by our advanced AI based on your dietary preferences, goals, and restrictions.",
      icon: "🤖"
    },
    {
      title: "Progress Tracking",
      description: "Monitor your weight, water intake, and nutrition with beautiful charts and progress reports.",
      icon: "📊"
    },
    {
      title: "Smart Recommendations",
      description: "Our system learns from your habits and preferences to suggest better meal options over time.",
      icon: "✨"
    },
    {
      title: "Dietary Customization",
      description: "Vegetarian, vegan, keto, gluten-free - we support all major dietary preferences and restrictions.",
      icon: "🥗"
    },
    {
      title: "Mobile Friendly",
      description: "Access your meal plans and track progress from any device, anywhere.",
      icon: "📱"
    },
    {
      title: "Motivational Tools",
      description: "Streaks and achievements to keep you motivated on your health journey.",
      icon: "🏆"
    }
  ];

  return (
    <>
    <Header /> 
    <div className="info-page">
      <div className="info-header">
        <h1>Features</h1>
        <p>Discover what makes DietAI the perfect companion for your health journey</p>
      </div>
      
      <div className="features-grid">
        {features.map((feature, index) => (
          <FeatureCard 
            key={index}
            title={feature.title}
            description={feature.description}
            icon={feature.icon}
          />
        ))}
      </div>
    </div>
    <Footer />
    </>
  );
};

export default FeaturesPage;